export enum EntityName {
    User= "User",
    Otp= "Otp",
    Post= "Post",
    Auth= "Auth",
    Comment= "Comment",
    Category= "Category",
    Tag= "Tag",
    Role= "Role",
    Permission= "Permission",
    Profile= "Profile",
    Setting= "Setting",
    File= "File",
    Notification= "Notification",
    Like= "Like",
    Report= "Report",
    Follow= "Follow",
    Bookmark= "Bookmark",
    Message= "Message",
    Conversation= "Conversation",
}