export enum EntityName {
    User = "User",
    Otp = "Otp",
    Post = "Post",
    Comment = "Comment",
    Category = "Category",
    Tag = "Tag",
    Role = "Role",
    Permission = "Permission",
    Profile = "Profile",
    Setting = "Setting",
    File = "File",
    Notification = "Notification",
    Like = "Like",
    Report = "Report",
    Follow = "Follow",
    Bookmark = "Bookmark",
    Message = "Message",
    Conversation = "Conversation",
    Blog = "Blog",
    BlogCategory = "BlogCategory",
    BlogLikes = "BlogLikes",
    BlogBookmarks = "BlogBookmarks",
    BlogComments = "BlogComments",
    image=  "image"
}
